### ISSUE TITLE
Not working with webpack

### ISSUE THREAD

**Issue by aqlx86** [squareboat/nest-console#13]
what changes should be made on the cli file to make this work, I have webpack set true in nest-cli.json

`"@squareboat/nest-console": "^1.1.1",`

```
at Reflect.getMetadata (**/node_modules/reflect-metadata/Reflect.js:354:23)
    at DependenciesScanner.isInjectable (**/node_modules/@nestjs/core/scanner.js:345:26)
    at DependenciesScanner.insertModule (**/node_modules/@nestjs/core/scanner.js:73:18)
    at DependenciesScanner.scanForModules (**/node_modules/@nestjs/core/scanner.js:34:43)
    at DependenciesScanner.scan (**/node_modules/@nestjs/core/scanner.js:27:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async **/node_modules/@nestjs/core/nest-factory.js:107:17
    at async Function.asyncRun (**/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
    at async NestFactoryStatic.initialize (**/node_modules/@nestjs/core/nest-factory.js:106:13)
    at async NestFactoryStatic.createApplicationContext (**/node_modules/@nestjs/core/nest-factory.js:81:9)
error Command failed with exit code 1.
```

**Comment by aqlx86** [comment]
Fixed by updating my package.json script, the issue was it could not find aliased paths. but its really slow executing `yarn cli list` takes 30 seconds

`"cli": "TS_NODE_PROJECT=./tsconfig.json ts-node -r tsconfig-paths/register cli",`
